---
# Series of tasks to upgrade/downgrade Splunkd to systemd

- include_tasks: convert_to_systemd.yml
  tags: upgrade

- include_tasks: unit_file.yml
  tags: upgrade

- include_tasks: convert_to_splunkd.yml
  tags: downgrade
