- name: Print Linux distribution and version
  hosts: splunk_servers
  tasks:
   - name: Print OS and Version
     command: cat /etc/system-release
     when: (ansible_distribution == "CentOS") and
           (ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7")
   - debug: 
      msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
